#!/bin/bash
# build_source_bundle.sh — produce the dev source bundle for the release image.
#
# When the release stage of Dockerfile.multi is built with KEEP_SOURCE=1, this
# script combines the wheel-stage trt-llm source + the install-stage UCX/NIXL
# trees + the wheel-stage UCXX FetchContent dir into ONE zstd-compressed +
# openssl-AES-256-CBC-encrypted bundle at /opt/src/source-bundle.tar.zst.enc.
#
# Bundle layout (paths relative to "/" — extract with `tar -xf - -C /`):
#   ./app/tensorrt_llm/   wheel-stage source minus regenerable/dev-tool excludes
#   ./opt/src/ucx/        pristine UCX working tree (.git stripped)
#   ./opt/src/nixl/       pristine NIXL working tree (.git stripped)
#   ./opt/src/ucxx/       pristine UCXX from cmake FetchContent
#
# Bind-mount expectations (set up by the calling RUN in Dockerfile.multi):
#   /tmp/_wheel_src       wheel-stage's /src/tensorrt_llm        (read-only)
#   /tmp/_keep_ucxx       wheel-stage's cpp/build/_deps/ucxx-src (read-only)
#
# Filesystem expectations (created during devel stage by install_ucx.sh /
# install_nixl.sh when invoked with KEEP_SOURCE=1):
#   /opt/src/ucx          (moved into bundle, /opt/src/ucx is removed after)
#   /opt/src/nixl         (same)
#
# Env-var inputs:
#   image_src_key         encryption passphrase for the openssl pipeline
#
# Output: /opt/src/source-bundle.tar.zst.enc
#
# The caller (Dockerfile.multi's release stage) is responsible for the
# KEEP_SOURCE gate — this script always builds the bundle when invoked.

set -ex

if [ -z "${image_src_key:-}" ]; then
    echo "image_src_key must be set" >&2
    exit 1
fi

WHEEL_SRC=/tmp/_wheel_src
UCXX_SRC=/tmp/_keep_ucxx
STAGE=/tmp/_bundle
OUT=/opt/src/source-bundle.tar.zst.enc

# Stage everything under /tmp/_bundle/ so the final tarball has paths
# like ./app/tensorrt_llm/... and ./opt/src/ucx/... — extract-to-/
# puts each piece in its final spot inside the dev container.
mkdir -p "$STAGE/app/tensorrt_llm" "$STAGE/opt/src" /opt/src

# 1. trt-llm wheel-stage source (with excludes) → bundle stage.
#
# Excludes — these are either regenerated by the in-pod build (so
# shipping them is wasteful) or live in dist-packages already
# (so the dev image has its own copy):
#   build artifacts:   ./build, ./cpp/build, **/build/_deps, **/generated
#   regenerable cubin: cubin/fmha_cubin.{h,cpp}  (build_wheel.py --generate_fmha)
#   working tree:      .git
#   caches:            .venv*, __pycache__, *.pyc, .pytest_cache, .ruff_cache, .mypy_cache
#   wheel outputs:     tensorrt_llm/{libs,bin,include}  (live in dist-packages)
(
    cd "$WHEEL_SRC" && tar -cf - \
        --exclude='./build' \
        --exclude='./cpp/build' \
        --exclude='**/build/_deps' \
        --exclude='**/generated' \
        --exclude='./cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/cubin/fmha_cubin.h' \
        --exclude='./cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/cubin/fmha_cubin.cpp' \
        --exclude='.git' \
        --exclude='.venv*' \
        --exclude='__pycache__' \
        --exclude='*.pyc' \
        --exclude='.pytest_cache' \
        --exclude='.ruff_cache' \
        --exclude='.mypy_cache' \
        --exclude='./tensorrt_llm/libs' \
        --exclude='./tensorrt_llm/bin' \
        --exclude='./tensorrt_llm/include' \
        .
) | tar -xf - -C "$STAGE/app/tensorrt_llm"

# 2. UCX — filesystem dir from install_ucx.sh. Move into bundle stage
# (rather than copy) so /opt/src/ucx is gone afterward — we don't want
# both the raw dir and the bundle in the image.
[ -d /opt/src/ucx ]  && mv /opt/src/ucx  "$STAGE/opt/src/ucx"

# 3. NIXL — same pattern. install_nixl.sh already trimmed builddir/
# and extracted meson subprojects whose tarballs survive in packagecache/.
[ -d /opt/src/nixl ] && mv /opt/src/nixl "$STAGE/opt/src/nixl"

# 4. UCXX — read-only bind mount, so cp. Strip nested .git dirs that
# came from cmake FetchContent's clone (.gitattributes, .gitignore stay).
cp -a "$UCXX_SRC" "$STAGE/opt/src/ucxx"
find "$STAGE/opt/src/ucxx" -name .git -prune -exec rm -rf {} +

# 5. Bundle into single encrypted+compressed tarball.
# Compress BEFORE encrypt — encrypted output is high-entropy and
# would defeat any compression applied after.
(
    cd "$STAGE" && tar -cf - . \
        | zstd -19 -T0 \
        | openssl enc -aes-256-cbc -pbkdf2 -salt \
            -pass "pass:$image_src_key" \
        > "$OUT"
)

# Build-log size report — helpful for tracking compression ratio
# across CUDA arch combinations and source-tree growth over time.
echo "── source-bundle sizes ──"
du -sh "$STAGE/app/tensorrt_llm" \
       "$STAGE/opt/src/ucx" \
       "$STAGE/opt/src/nixl" \
       "$STAGE/opt/src/ucxx" 2>/dev/null
du -sh "$STAGE"
ls -lh "$OUT"
echo "─────────────────────────"

rm -rf "$STAGE"
